### ISSUE TITLE
possible code duplication

### ISSUE THREAD

**Issue by frankbraun** [decred/dcraddrgen#11]
The definitions https://github.com/decred/dcraddrgen/blob/8ffad866906ff1ce7240905f463229fea9f52a56/address/address.go#L15-L18 seem to be unused duplications from the definitions in https://github.com/decred/dcraddrgen/blob/8ffad866906ff1ce7240905f463229fea9f52a56/main.go and can probably be removed.

**Comment by jcvernaleo** [comment]
You are correct that there is some duplicated code in there.  The reason is that dcraddrgen depens on some bits of dcrd/dcrwallet that haven't been released yet.  Once those are released I'll remove a lot of dcraddrgen and let it just import the dcrd repos as needed from github.  So until then I don't want to mess with those files too much so it simplifies the change to this code when dcrd comes out.

Hope that explanation makes sense and thanks for looking!

**Comment by frankbraun** [comment]
Makes sense, I'm looking forward to the release of dcrd/dcrwallet!
