### ISSUE TITLE
Need to vendor some packages

### ISSUE THREAD

**Issue by davecgh** [decred/dcraddrgen#2]
In order to have better control over the dependencies, I would suggest forking the things that are need in the decred org and updating the import paths accordingly.  This is the same way btcsuite handles it currently.  For the future, we have been evaluating glide for handling the dependency control issue in btcsuite, but glide is still under development and not quite ready for prime time yet.

Notice from the output below that it's pulling dependencies from external sources.

```base
$ go get -u -v github.com/decred/dcraddrgen/...
github.com/decred/dcraddrgen (download)
*** github.com/btcsuite/btcd (download)
*** github.com/btcsuite/fastsha256 (download)
*** github.com/btcsuite/golangcrypto (download)
*** github.com/dchest/blake256 (download)
*** github.com/btcsuite/fastsha256
*** github.com/btcsuite/golangcrypto/ripemd160
*** github.com/dchest/blake256
*** github.com/btcsuite/btcd/btcec
*** github.com/btcsuite/btcd/wire
github.com/decred/dcraddrgen/chainhash
github.com/decred/dcraddrgen/base58
github.com/decred/dcraddrgen/address
github.com/decred/dcraddrgen/pgpwordlist
github.com/decred/dcraddrgen/hdkeychain
github.com/decred/dcraddrgen
```

Also, I believe there should no longer be any reason for `github.com/btcsuite/fastsha256` since the only reason btcsuite still uses it is for access to the midstate needed by the deprecated `getwork` RPC call.  The stdlib has all of the optimizations provided by the package, so there is no advantage to using it over the stdlib unless the midstate is needed.

**Comment by jcvernaleo** [comment]
Thanks for catching fastsha.  I had it in the back of my mind to kill that but never got around to it.

I'll definitely fork/vendor blake256.  I guess I can fork/vendor github.com/btcsuite/golangcrypto/ripemd160 but it seems unnecessary since that is already a forked version from btcsuite and for some reason I trust them :)

As for the other btcsuite imports I need to look and see why they are being imported.  We probably already have the code forked and should use that.  But as pointed out in #3 and #4, this project is in a weird state since code it depends on hasn't been released yet so it has things copied and pasted into it that I will be much happier when I can remove.

**Comment by rasrenato** [comment]
verdade jc

**Comment by jcvernaleo** [comment]
I vendored the non-btcsuite repo and now we use that.

As for the btcsuite deps those will mostly be dealt with when the rest of the code is released so I'm closing this issue for now.

Thanks for pointing out the need to vendor blake256.  Glad to get that done.
