### ISSUE TITLE
Decred should have a unique MainHDCoinType set

### ISSUE THREAD

**Issue by jyap808** [decred/dcraddrgen#9]
Currently:
https://github.com/decred/dcraddrgen/blob/master/main.go#L68-L69

````
// MainHDCoinType is the cointype for mainnet.
var MainHDCoinType = uint32(20)
```

Index 20 for BIP-0044 already reserved.

http://doc.satoshilabs.com/slips/slip-0044.html#registered-coin-types

Decred should put in a pull request to the satoshilabs repo for a unique coin type.

https://github.com/satoshilabs/docs/blob/master/slips/slip-0044.rst

Accepting tips: DsjEawVsKJgbEaqGzRB1mBtVQsTjqbw58Uj

**Comment by jrick** [comment]
We've decided to stick with the non-standard derivation.  If we realized this sooner, we could have reserved a coin type, but as it stands (with airdrop addresses using this particular derivation), we feel it would be a greater hassle to change it now rather than being incompatible and requiring users of DigiByte to backup two seeds instead of one.
